### ISSUE TITLE
Suggestion: Retro Sci Fi

### ISSUE THREAD

**Issue by Botspot** [phoenixbyrd/Screensavers#1]
Nice collection of screensavers!

Would you be able to add Retro Sci-Fi?
![screenshot](https://www.screensaversplanet.com/img/screenshots/screensavers/large/retro-sci-fi-1.png)
![screenshot](https://www.screensaversplanet.com/img/screenshots/screensavers/large/retro-sci-fi-blue-edition-1.png)
- [Link to the green version](https://www.screensaversplanet.com/screensavers/retro-sci-fi-522/)
- [Link to the blue version](https://www.screensaversplanet.com/screensavers/retro-sci-fi-blue-edition-1702/)

**Comment by phoenixbyrd** [comment]
Will get these added today!

**Comment by phoenixbyrd** [comment]
Both added now.

**Comment by Botspot** [comment]
How did you do it? On my system, Wine failed to install the exe and it wouldn't run.

**Comment by Botspot** [comment]
Any ideas? It seems to have installed properly, but systemd reports there being no service named "`screensaver`".
```
Reload service daemon: sudo systemctl daemon-reload
Verify service is running: sudo systemctl status screensaver
Enable on startup: sudo systemctl enable screensaver
Start 3dpipes service: sudo systemctl start screensaver
Stop 3dpipes service: sudo systemctl stop screensaver
pi@raspberrypi:~ $ sudo systemctl start screensaver
Failed to start screensaver.service: Unit screensaver.service not found.
pi@raspberrypi:~ $ 
```
And yes, this is me trying to install RetroScifiBlue, even though it mentions 3dpipes for some reason. Also I noticed that if there were any earlier errors, they are gone now because the screen was cleared. :(
