### ISSUE TITLE
Consider removing /home/pi from everything

### ISSUE THREAD

**Issue by Botspot** [phoenixbyrd/Screensavers#2]
I briefly looked at one of your scripts and noticed that it contained many references to /home/pi. This will be problematic for Ubuntu users, and for anyone else who doesn't use RPiOS's default user `pi` account.

Solution: Change lines like this one:
```
cp RetroSciFi_Blue.scr '/home/pi/.screensavers/drive_c/windows/'
```
To this:
```
cp RetroSciFi_Blue.scr ~/'.screensavers/drive_c/windows/'
```
Or this:
```
cp RetroSciFi_Blue.scr "$HOME/.screensavers/drive_c/windows/"
```

**Comment by phoenixbyrd** [comment]
Scripts have been redone and improved on.

**Comment by phoenixbyrd** [comment]
Realized after rewriting everything that every single screensaver broke. Tried various methods to resolve the issue to no avail. Reverted back to /home/pi and updated readme to reflect what this project is intended for. This was originally intended for Twister OS and is now specifically stated as such. If you'd like to use these on other distros, feel free to fork this project and maintain a version for other distros. I use only Twister OS and have no desire to support other distros.

**Comment by Botspot** [comment]
> Realized after rewriting everything that every single screensaver broke. Tried various methods to resolve the issue to no avail.

That's strange. Maybe it wasn't done properly? I understand your lack of interest in doing this, so I'll give it a try.
